#server:
#  port: 7000
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 10.250.68.222:8848
#    gateway:
#      discovery:
#        locator:
#          enabled: true    # ?gateway????nacos?????

