server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
      server-addr: 10.250.68.222:8848
    gateway:
      discovery:
        locator:
        enabled: true # ?gateway????nacos?????
      routes:                           # ????[?? ???????????????????????]
        - id: product_route             # ???????, ????
          uri: lb://service-product     # lb????nacos??????????,?????????
          order: 1                      # ??????,????????
          predicates:                   # ??(????????????)
            - Path=/product-serv/**     # ???????Path??????,???????
          filters:                      # ???,????????????????????????
            - StripPrefix=1             # ??????1???
